name: Deploy GitHub AI Review Bot (Static Web App + Function)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-review-bot:
    name: Deploy GitHub AI Review Bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          api_location: 'api'
          output_location: ''

      - name: Install Azure CLI Search Extension
        run: az extension add --name search-documents

      - name: Re-index guidelines
        run: |
          echo "Triggering AI Search reindexer..."
          az search indexer run --service-name aicodereview-search --name guideline-indexer --resource-group AI-CodeReview-RG
